# Generated by Django 4.2.3 on 2023-07-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desination',
            new_name='Destination',
        ),
    ]
